services:
  cliente-persona-api:
    image: carlosfls/cliente-persona-api:1.1
    mem_limit: 700m
    container_name: cliente-persona-api
    ports:
    - "8081:8081"
    networks:
      - expenses-network
    depends_on:
      - cuenta-movimiento-api

  cuenta-movimiento-api:
    image: carlosfls/cuenta-movimiento-api:1.1
    mem_limit: 700m
    container_name: cuenta-movimiento-api
    ports:
    - "8080:8080"
    networks:
      - expenses-network

networks:
  expenses-network:
