services:
  cliente-persona-api:
    image: sha256:42a9f6446ae54fd7dab9b44e3b74e227f8fb3e52b134e1637ca0cebe20d6d4fa
    mem_limit: 700m
    container_name: cliente-persona-api
    ports:
    - "8081:8081"
    networks:
      - expenses-network
    depends_on:
      - cuenta-movimiento-api

  cuenta-movimiento-api:
    image: sha256:0720093fc21866c0d62e21b2973ea900081ce683e7f34d1568a36d8868d241d5
    mem_limit: 700m
    container_name: cuenta-movimiento-api
    ports:
    - "8080:8080"
    networks:
      - expenses-network

networks:
  expenses-network: