spring:
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/db_assingment
    username: postgres
    password: postgres

 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true

config:
  active:
    on-profile: dev

feign:
  cuenta_movimiento:
    uri: http://cuenta-movimientos-api:8080/api