spring:
 datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

 jpa:
   hibernate:
     ddl-auto: none
   show-sql: false

config:
  active:
    on-profile: dev

feign:
  cuenta_movimiento:
    uri: http://cuenta-movimientos-api:8080/api