spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    consumer:
      bootstrap-servers: localhost:9092 localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: delete-cuenta-topic-events
      properties:
        spring:
          json:
            trusted:
              packages: '*'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

config:
  active:
    on-profile: dev


feign:
  cliente_persona:
    uri: ${FEIGN_CLIENTE_PERSONA_URI}
