spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/db_assingment
    username: postgres
    password: postgres

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

config:
  active:
    on-profile: dev


feign:
  cliente_persona:
    uri: http://cliente-persona-api:8081/api
