spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

config:
  active:
    on-profile: dev


feign:
  cliente_persona:
    uri: ${FEIGN_CLIENTE_PERSONA_URI}
